# Barely - created by AayuShen.
# Writes build\tap_hash.h with the SHA-256 of barely_tap.dll, so barely.exe refuses
# to load any DLL other than the one it was built with.
param([Parameter(Mandatory)][string]$Dll, [Parameter(Mandatory)][string]$Out)
$ErrorActionPreference = "Stop"
$hash = (Get-FileHash -LiteralPath $Dll -Algorithm SHA256).Hash
Set-Content -LiteralPath $Out -Encoding ascii -Value @(
    "// Generated by tools\embed_hash.ps1. Do not edit.",
    "#pragma once",
    "#define BARELY_TAP_SHA256 `"$hash`""
)
Write-Host "barely_tap.dll SHA-256: $hash"
