// Barely — a transparent Windows 11 taskbar with no background process.
// Created by AayuShen. Copyright (c) 2026 AayuShen. All rights reserved.
//
// barely.exe / barelyw.exe — saves the opacity, loads barely_tap.dll into explorer once,
// then exits. barelyw.exe is the same program built as a GUI app (no console window) for
// autostart at logon.
//
// Security checks before anything is loaded into explorer:
//   * DLL search is restricted to System32, so a planted DLL next to the exe is ignored.
//   * Refuses to run elevated; Barely only ever needs normal user rights.
//   * barely_tap.dll must match the SHA-256 recorded at build time, and the file is held
//     open without write/delete sharing from the check until explorer has loaded it,
//     so it cannot be swapped in between.
//   * The target must be %SystemRoot%\explorer.exe in the caller's own session.
//   * A mutex keeps two copies from injecting at the same time.

#include <windows.h>
#include <bcrypt.h>
#include <tlhelp32.h>

#include <cstdarg>
#include <cstdio>
#include <cwchar>
#include <cwctype>
#include <string>
#include <vector>

#include "barely_shared.h"
#include "tap_hash.h"  // generated by build.cmd: #define BARELY_TAP_SHA256 "<hex>"

namespace {

constexpr wchar_t kRunKey[] = L"Software\\Microsoft\\Windows\\CurrentVersion\\Run";
constexpr wchar_t kRunValue[] = L"Barely";

void Say(bool error, const wchar_t* fmt, ...) {
    wchar_t buf[1024];
    va_list ap;
    va_start(ap, fmt);
    vswprintf_s(buf, fmt, ap);
    va_end(ap);
#ifdef BARELY_GUI
    if (error) MessageBoxW(nullptr, buf, L"Barely", MB_ICONERROR);
#else
    fwprintf(error ? stderr : stdout, L"%ls\n", buf);
#endif
}

std::wstring SiblingPath(const wchar_t* fileName) {
    wchar_t self[MAX_PATH];
    DWORD n = GetModuleFileNameW(nullptr, self, MAX_PATH);
    std::wstring path(self, n);
    return path.substr(0, path.find_last_of(L'\\') + 1) + fileName;
}

bool IsElevated() {
    HANDLE token;
    if (!OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &token)) return false;
    TOKEN_ELEVATION elevation{};
    DWORD size = sizeof(elevation);
    bool elevated = GetTokenInformation(token, TokenElevation, &elevation, size, &size) &&
                    elevation.TokenIsElevated;
    CloseHandle(token);
    return elevated;
}

// Opens the DLL without write/delete sharing and checks its SHA-256. On success the
// handle is returned and must stay open until explorer has loaded the file.
HANDLE OpenVerifiedTap(const std::wstring& path) {
    HANDLE file = CreateFileW(path.c_str(), GENERIC_READ, FILE_SHARE_READ, nullptr, OPEN_EXISTING,
                              FILE_ATTRIBUTE_NORMAL, nullptr);
    if (file == INVALID_HANDLE_VALUE) return nullptr;

    LARGE_INTEGER size{};
    std::vector<BYTE> data;
    DWORD read = 0;
    if (!GetFileSizeEx(file, &size) || size.QuadPart <= 0 || size.QuadPart > 16 * 1024 * 1024)
        goto fail;
    data.resize(static_cast<size_t>(size.QuadPart));
    if (!ReadFile(file, data.data(), static_cast<DWORD>(data.size()), &read, nullptr) ||
        read != data.size())
        goto fail;
    {
        BYTE digest[32];
        if (!BCRYPT_SUCCESS(BCryptHash(BCRYPT_SHA256_ALG_HANDLE, nullptr, 0, data.data(),
                                       static_cast<ULONG>(data.size()), digest, sizeof(digest))))
            goto fail;
        char hex[65];
        for (int i = 0; i < 32; ++i) sprintf_s(hex + i * 2, 3, "%02X", digest[i]);
        if (_stricmp(hex, BARELY_TAP_SHA256) != 0) goto fail;
    }
    return file;
fail:
    CloseHandle(file);
    return nullptr;
}

bool SaveOpacity(DWORD percent) {
    return RegSetKeyValueW(HKEY_CURRENT_USER, kRegKey, kRegOpacity, REG_DWORD, &percent,
                           sizeof(percent)) == ERROR_SUCCESS;
}

bool LoadOpacity(DWORD& percent) {
    DWORD size = sizeof(percent);
    return RegGetValueW(HKEY_CURRENT_USER, kRegKey, kRegOpacity, RRF_RT_REG_DWORD, nullptr,
                        &percent, &size) == ERROR_SUCCESS;
}

// The taskbar may not exist yet right after logon, so wait for it.
DWORD WaitForExplorer(DWORD timeoutMs) {
    for (DWORD waited = 0;; waited += 500) {
        if (HWND tray = FindWindowW(L"Shell_TrayWnd", nullptr)) {
            DWORD pid = 0;
            GetWindowThreadProcessId(tray, &pid);
            if (pid) return pid;
        }
        if (waited >= timeoutMs) return 0;
        Sleep(500);
    }
}

// The window class is easy to fake, so check who actually owns it.
bool IsTrustedExplorer(DWORD pid) {
    DWORD ours = 0, theirs = 0;
    if (!ProcessIdToSessionId(GetCurrentProcessId(), &ours) ||
        !ProcessIdToSessionId(pid, &theirs) || ours != theirs)
        return false;
    HANDLE process = OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, FALSE, pid);
    if (!process) return false;
    bool ok = IsSystemExplorer(process);
    CloseHandle(process);
    return ok;
}

bool TapLoaded(DWORD pid) {
    HANDLE snap = CreateToolhelp32Snapshot(TH32CS_SNAPMODULE, pid);
    if (snap == INVALID_HANDLE_VALUE) return false;
    MODULEENTRY32W me{sizeof(me)};
    bool found = false;
    for (BOOL ok = Module32FirstW(snap, &me); ok && !found; ok = Module32NextW(snap, &me))
        found = _wcsicmp(me.szModule, kTapDllName) == 0;
    CloseHandle(snap);
    return found;
}

HRESULT Inject(DWORD pid, const std::wstring& tapPath) {
    using InitializeXamlDiagnosticsExFn =
        HRESULT(WINAPI*)(LPCWSTR, DWORD, LPCWSTR, LPCWSTR, CLSID, LPCWSTR);

    HMODULE xaml = LoadLibraryExW(L"Windows.UI.Xaml.dll", nullptr, LOAD_LIBRARY_SEARCH_SYSTEM32);
    if (!xaml) return HRESULT_FROM_WIN32(GetLastError());
    auto ixde = reinterpret_cast<InitializeXamlDiagnosticsExFn>(
        GetProcAddress(xaml, "InitializeXamlDiagnosticsEx"));
    if (!ixde) return HRESULT_FROM_WIN32(GetLastError());

    // An endpoint name can already be taken (e.g. by a dev tool), so try a few.
    HRESULT hr = E_FAIL;
    for (int i = 1; i <= 10; ++i) {
        wchar_t endpoint[64];
        swprintf_s(endpoint, L"VisualDiagConnection%d", i);
        hr = ixde(endpoint, pid, nullptr, tapPath.c_str(), CLSID_BarelyTap, nullptr);
        if (SUCCEEDED(hr)) break;
    }
    return hr;
}

bool SetAutostart(bool on) {
    if (!on) {
        LSTATUS s = RegDeleteKeyValueW(HKEY_CURRENT_USER, kRunKey, kRunValue);
        return s == ERROR_SUCCESS || s == ERROR_FILE_NOT_FOUND;
    }
    // Quoted, so a path with spaces can't be hijacked by a planted "E:\Program.exe".
    std::wstring cmd = L"\"" + SiblingPath(L"barelyw.exe") + L"\"";
    return RegSetKeyValueW(HKEY_CURRENT_USER, kRunKey, kRunValue, REG_SZ, cmd.c_str(),
                           static_cast<DWORD>((cmd.size() + 1) * sizeof(wchar_t))) == ERROR_SUCCESS;
}

int Apply(DWORD percent) {
    if (!SaveOpacity(percent)) {
        Say(true, L"Could not write HKCU\\%ls.", kRegKey);
        return 1;
    }
    DWORD pid = WaitForExplorer(60'000);
    if (!pid) {
        Say(true, L"Taskbar not found (is explorer.exe running?).");
        return 1;
    }
    if (!IsTrustedExplorer(pid)) {
        Say(true, L"The taskbar window is not owned by %%SystemRoot%%\\explorer.exe. Refusing.");
        return 1;
    }
    if (TapLoaded(pid)) {  // already inside explorer; it saw the registry change
        Say(false, L"Taskbar opacity set to %lu%%.", percent);
        return 0;
    }

    std::wstring tap = SiblingPath(kTapDllName);
    HANDLE lock = OpenVerifiedTap(tap);
    if (!lock) {
        Say(true, L"%ls is missing or does not match this build of Barely. Refusing to load it.",
            kTapDllName);
        return 1;
    }
    HRESULT hr = Inject(pid, tap);
    for (int i = 0; SUCCEEDED(hr) && i < 50 && !TapLoaded(pid); ++i) Sleep(100);
    bool loaded = SUCCEEDED(hr) && TapLoaded(pid);
    CloseHandle(lock);

    if (FAILED(hr)) {
        Say(true, L"InitializeXamlDiagnosticsEx failed: 0x%08lX", static_cast<unsigned long>(hr));
        return 1;
    }
    if (!loaded) {
        Say(true, L"Explorer did not load %ls.", kTapDllName);
        return 1;
    }
    Say(false, L"Taskbar opacity set to %lu%%.", percent);
    return 0;
}

void Usage() {
    Say(false,
        L"Barely %ls by AayuShen\n"
        L"\n"
        L"Usage:\n"
        L"  barely              apply the saved opacity (default 0 = fully clear)\n"
        L"  barely <0-100>      set taskbar background opacity in percent\n"
        L"  barely --restore    back to the stock taskbar and disable autostart\n"
        L"  barely --autostart on|off\n"
        L"  barely --version\n"
        L"\n"
        L"Nothing stays running. Re-run after restarting explorer.exe.",
        kVersion);
}

int Run(int argc, wchar_t** argv) {
    if (argc == 1) {
        DWORD percent = 0;
        LoadOpacity(percent);
        return Apply(percent);
    }

    std::wstring arg = argv[1];
    if (argc == 2 && (arg == L"--help" || arg == L"-h" || arg == L"/?")) return Usage(), 0;
    if (argc == 2 && arg == L"--version") {
        Say(false, L"Barely %ls by AayuShen", kVersion);
        return 0;
    }
    if (argc == 2 && arg == L"--restore") {
        RegDeleteKeyValueW(HKEY_CURRENT_USER, kRegKey, kRegOpacity);
        SetAutostart(false);
        Say(false, L"Restored the stock taskbar. Autostart disabled.");
        return 0;
    }
    if (argc == 3 && arg == L"--autostart") {
        std::wstring v = argv[2];
        if (v != L"on" && v != L"off") return Usage(), 1;
        if (v == L"on" && GetFileAttributesW(SiblingPath(L"barelyw.exe").c_str()) ==
                              INVALID_FILE_ATTRIBUTES) {
            Say(true, L"barelyw.exe not found next to barely.exe.");
            return 1;
        }
        if (!SetAutostart(v == L"on")) {
            Say(true, L"Could not update the Run key.");
            return 1;
        }
        Say(false, L"Autostart %ls.", v == L"on" ? L"enabled" : L"disabled");
        return 0;
    }

    wchar_t* end = nullptr;
    unsigned long percent = wcstoul(arg.c_str(), &end, 10);
    if (argc != 2 || arg.empty() || arg.size() > 3 || !std::iswdigit(arg[0]) || *end ||
        percent > 100)
        return Usage(), 1;
    return Apply(percent);
}

}  // namespace

int wmain(int argc, wchar_t** argv) {
    // Never pick up DLLs from the current or application directory.
    SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_SYSTEM32);

    if (IsElevated()) {
        Say(true, L"Run Barely as a normal user, not as administrator. It doesn't need admin rights.");
        return 1;
    }

    HANDLE mutex = CreateMutexW(nullptr, FALSE, L"Local\\Barely.Injector");
    if (mutex) {
        DWORD w = WaitForSingleObject(mutex, 90'000);
        if (w != WAIT_OBJECT_0 && w != WAIT_ABANDONED) {
            Say(true, L"Another copy of Barely is still running.");
            return 1;
        }
    }
    int rc = Run(argc, argv);
    if (mutex) {
        ReleaseMutex(mutex);
        CloseHandle(mutex);
    }
    return rc;
}
