// Barely — a transparent Windows 11 taskbar with no background process.
// Created by AayuShen. Copyright (c) 2026 AayuShen. Licensed under the MIT License.
//
// barely.exe / barelyw.exe — saves settings, loads barely_tap.dll into explorer once, then
// exits. barelyw.exe is the same program built as a GUI app (no console window), used for
// autostart, the auto-repair task and the settings window.
//
// Security checks before anything is loaded into explorer:
//   * DLL search is restricted to System32, so a planted DLL next to the exe is ignored.
//   * Refuses to run elevated; Barely only ever needs normal user rights.
//   * barely_tap.dll must match the SHA-256 recorded at build time, and the file is held
//     open without write/delete sharing from the check until explorer has loaded it,
//     so it cannot be swapped in between.
//   * The target must be %SystemRoot%\explorer.exe in the caller's own session.
//   * A mutex keeps two copies from injecting at the same time.
//   * Helper tools (schtasks.exe) are started by absolute System32 path.

#include <windows.h>
#include <bcrypt.h>
#include <commctrl.h>
#include <commdlg.h>
#include <sddl.h>
#include <tlhelp32.h>

#include <cstdarg>
#include <cstdio>
#include <cwchar>
#include <cwctype>
#include <optional>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

#include "barely_shared.h"
#include "tap_hash.h"  // generated by build.cmd: #define BARELY_TAP_SHA256 "<hex>"

using namespace std::literals;

namespace {

enum ExitCode : int {
    kOk = 0,
    kFailed = 1,
    kUsage = 2,
    kNotRecognized = 3,  // loaded, but the taskbar layout wasn't recognized
    kIntegrity = 4,      // barely_tap.dll missing or modified
    kElevated = 5,
    kUnsupported = 6,    // not Windows 11
};

constexpr wchar_t kRunKey[] = L"Software\\Microsoft\\Windows\\CurrentVersion\\Run";
constexpr wchar_t kRunValue[] = L"Barely";
constexpr wchar_t kTaskName[] = L"Barely Auto-Repair";
constexpr DWORD kMinBuild = 22000;  // Windows 11
// Builds Barely has been verified on. Others likely work (same taskbar XAML) but get a note.
constexpr DWORD kTestedBuilds[] = {26200};

bool g_quiet = false;  // --ensure never shows anything

void Say(bool error, const wchar_t* fmt, ...) {
    if (g_quiet) return;
    wchar_t buf[4096];
    va_list ap;
    va_start(ap, fmt);
    vswprintf_s(buf, fmt, ap);
    va_end(ap);
#ifdef BARELY_GUI
    if (error) MessageBoxW(nullptr, buf, L"Barely", MB_ICONERROR);
#else
    fwprintf(error ? stderr : stdout, L"%ls\n", buf);
#endif
}

class UniqueHandle {
public:
    explicit UniqueHandle(HANDLE h = nullptr) : h_(h == INVALID_HANDLE_VALUE ? nullptr : h) {}
    UniqueHandle(UniqueHandle&& o) noexcept : h_(std::exchange(o.h_, nullptr)) {}
    UniqueHandle(const UniqueHandle&) = delete;
    UniqueHandle& operator=(const UniqueHandle&) = delete;
    ~UniqueHandle() {
        if (h_) CloseHandle(h_);
    }
    HANDLE get() const { return h_; }
    explicit operator bool() const { return h_ != nullptr; }

private:
    HANDLE h_;
};

std::wstring SiblingPath(const wchar_t* fileName) {
    wchar_t self[MAX_PATH];
    DWORD n = GetModuleFileNameW(nullptr, self, MAX_PATH);
    std::wstring path(self, n);
    return path.substr(0, path.find_last_of(L'\\') + 1) + fileName;
}

std::wstring SystemTool(const wchar_t* exe) {
    wchar_t dir[MAX_PATH];
    GetSystemDirectoryW(dir, MAX_PATH);
    return L"\"" + std::wstring(dir) + L"\\" + exe + L"\"";
}

DWORD RunHidden(std::wstring cmdline) {
    STARTUPINFOW si{sizeof(si)};
    PROCESS_INFORMATION pi{};
    if (!CreateProcessW(nullptr, cmdline.data(), nullptr, nullptr, FALSE, CREATE_NO_WINDOW,
                        nullptr, nullptr, &si, &pi))
        return MAXDWORD;
    WaitForSingleObject(pi.hProcess, 30'000);
    DWORD code = MAXDWORD;
    GetExitCodeProcess(pi.hProcess, &code);
    CloseHandle(pi.hThread);
    CloseHandle(pi.hProcess);
    return code;
}

bool IsElevated() {
    HANDLE token;
    if (!OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &token)) return false;
    TOKEN_ELEVATION elevation{};
    DWORD size = sizeof(elevation);
    bool elevated = GetTokenInformation(token, TokenElevation, &elevation, size, &size) &&
                    elevation.TokenIsElevated;
    CloseHandle(token);
    return elevated;
}

DWORD WindowsBuild() {
    using RtlGetVersionFn = LONG(WINAPI*)(OSVERSIONINFOW*);
    HMODULE ntdll = GetModuleHandleW(L"ntdll.dll");
    auto fn = ntdll ? reinterpret_cast<RtlGetVersionFn>(GetProcAddress(ntdll, "RtlGetVersion"))
                    : nullptr;
    OSVERSIONINFOW v{sizeof(v)};
    return fn && fn(&v) == 0 ? v.dwBuildNumber : 0;
}

bool IsTestedBuild(DWORD build) {
    for (DWORD b : kTestedBuilds)
        if (b == build) return true;
    return false;
}

int CheckWindows(bool warnUntested) {
    DWORD build = WindowsBuild();
    if (build && build < kMinBuild) {
        Say(true, L"Barely needs Windows 11. This PC runs Windows build %lu.", build);
        return kUnsupported;
    }
    if (warnUntested && build && !IsTestedBuild(build))
        Say(false,
            L"Note: Windows build %lu hasn't been tested with Barely yet. If the taskbar doesn't "
            L"change, run `barely --diagnose`.",
            build);
    return kOk;
}

// ---- Settings ------------------------------------------------------------------------------

bool WriteSetting(const wchar_t* name, int value) {
    if (value == kUnset) {
        LSTATUS s = RegDeleteKeyValueW(HKEY_CURRENT_USER, kRegKey, name);
        return s == ERROR_SUCCESS || s == ERROR_FILE_NOT_FOUND;
    }
    DWORD v = static_cast<DWORD>(value);
    return RegSetKeyValueW(HKEY_CURRENT_USER, kRegKey, name, REG_DWORD, &v, sizeof(v)) ==
           ERROR_SUCCESS;
}

std::wstring Describe(const Settings& s) {
    if (s.opacity < 0) return L"stock taskbar (Barely is off)";
    auto pct = [](int v, const wchar_t* unset) {
        return v < 0 ? std::wstring(unset) : std::to_wstring(v) + L"%";
    };
    std::wstring out = L"opacity " + pct(s.opacity, L"") + L", border " + pct(s.stroke, L"same") +
                       L", maximized " + pct(s.maximized, L"off") + L", light mode " +
                       pct(s.light, L"same") + L", tint ";
    if (s.tint < 0) {
        out += L"none";
    } else {
        wchar_t hex[8];
        swprintf_s(hex, L"#%06X", s.tint);
        out += hex;
    }
    return out;
}

// ---- Integrity -----------------------------------------------------------------------------

bool HashMatches(HANDLE file) {
    LARGE_INTEGER size{};
    if (!GetFileSizeEx(file, &size) || size.QuadPart <= 0 || size.QuadPart > 16 * 1024 * 1024)
        return false;
    std::vector<BYTE> data(static_cast<size_t>(size.QuadPart));
    DWORD read = 0;
    if (!ReadFile(file, data.data(), static_cast<DWORD>(data.size()), &read, nullptr) ||
        read != data.size())
        return false;
    BYTE digest[32];
    if (!BCRYPT_SUCCESS(BCryptHash(BCRYPT_SHA256_ALG_HANDLE, nullptr, 0, data.data(),
                                   static_cast<ULONG>(data.size()), digest, sizeof(digest))))
        return false;
    char hex[65];
    for (int i = 0; i < 32; ++i) sprintf_s(hex + i * 2, 3, "%02X", digest[i]);
    return _stricmp(hex, BARELY_TAP_SHA256) == 0;
}

// Opens the DLL without write/delete sharing and checks its SHA-256. The returned handle
// must stay open until explorer has loaded the file.
UniqueHandle OpenVerifiedTap() {
    UniqueHandle file(CreateFileW(SiblingPath(kTapDllName).c_str(), GENERIC_READ, FILE_SHARE_READ,
                                  nullptr, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, nullptr));
    if (file && HashMatches(file.get())) return file;
    Say(true,
        L"%ls is missing or has been modified, so it doesn't match this copy of Barely.\n"
        L"Barely won't load it into Explorer. Download a fresh copy from %ls/releases",
        kTapDllName, kRepoUrl);
    return UniqueHandle();
}

// ---- Explorer ------------------------------------------------------------------------------

// The taskbar may not exist yet right after logon, so wait for it.
DWORD FindExplorer(DWORD timeoutMs) {
    for (DWORD waited = 0;; waited += 250) {
        if (HWND tray = FindWindowW(L"Shell_TrayWnd", nullptr)) {
            DWORD pid = 0;
            GetWindowThreadProcessId(tray, &pid);
            if (pid) return pid;
        }
        if (waited >= timeoutMs) return 0;
        Sleep(250);
    }
}

// The window class is easy to fake, so check who actually owns it.
bool IsTrustedExplorer(DWORD pid) {
    DWORD ours = 0, theirs = 0;
    if (!ProcessIdToSessionId(GetCurrentProcessId(), &ours) ||
        !ProcessIdToSessionId(pid, &theirs) || ours != theirs)
        return false;
    UniqueHandle process(OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION, FALSE, pid));
    return process && IsSystemExplorer(process.get());
}

bool TapLoaded(DWORD pid) {
    UniqueHandle snap(CreateToolhelp32Snapshot(TH32CS_SNAPMODULE, pid));
    if (!snap) return false;
    MODULEENTRY32W me{sizeof(me)};
    for (BOOL ok = Module32FirstW(snap.get(), &me); ok; ok = Module32NextW(snap.get(), &me))
        if (_wcsicmp(me.szModule, kTapDllName) == 0) return true;
    return false;
}

enum class TapState { NotLoaded, Outdated, Unrecognized, Working };

// What the DLL inside this explorer reports about itself.
TapState QueryTap(DWORD pid, DWORD waitMs) {
    if (!TapLoaded(pid)) return TapState::NotLoaded;
    for (DWORD waited = 0;; waited += 100) {
        DWORD rpid = 0, targets = 0;
        wchar_t version[32] = {};
        DWORD size = sizeof(version);
        bool const ours =
            ReadDword(kRegRuntimeKey, reg::kPid, rpid) && rpid == pid &&
            RegGetValueW(HKEY_CURRENT_USER, kRegRuntimeKey, reg::kTapVersion, RRF_RT_REG_SZ,
                         nullptr, version, &size) == ERROR_SUCCESS &&
            wcscmp(version, kVersion) == 0;
        if (ours && ReadDword(kRegRuntimeKey, reg::kTargets, targets) && targets > 0)
            return TapState::Working;
        if (waited >= waitMs) return ours ? TapState::Unrecognized : TapState::Outdated;
        Sleep(100);
    }
}

HRESULT Inject(DWORD pid, const std::wstring& tapPath) {
    using InitializeXamlDiagnosticsExFn =
        HRESULT(WINAPI*)(LPCWSTR, DWORD, LPCWSTR, LPCWSTR, CLSID, LPCWSTR);

    HMODULE xaml = LoadLibraryExW(L"Windows.UI.Xaml.dll", nullptr, LOAD_LIBRARY_SEARCH_SYSTEM32);
    if (!xaml) return HRESULT_FROM_WIN32(GetLastError());
    auto ixde = reinterpret_cast<InitializeXamlDiagnosticsExFn>(
        GetProcAddress(xaml, "InitializeXamlDiagnosticsEx"));
    if (!ixde) return HRESULT_FROM_WIN32(GetLastError());

    // An endpoint name can already be taken (e.g. by a dev tool), so try a few.
    HRESULT hr = E_FAIL;
    for (int i = 1; i <= 10; ++i) {
        wchar_t endpoint[64];
        swprintf_s(endpoint, L"VisualDiagConnection%d", i);
        hr = ixde(endpoint, pid, nullptr, tapPath.c_str(), CLSID_BarelyTap, nullptr);
        if (SUCCEEDED(hr)) break;
    }
    return hr;
}

// Explorer must see the same HKCU\Software\Barely we write. Inside some sandboxes and
// virtualized apps it doesn't, so wait for the DLL to echo the stamp we just wrote.
bool StampReachedExplorer(DWORD stamp) {
    for (int i = 0; i < 30; ++i) {
        DWORD seen = 0;
        if (ReadDword(kRegRuntimeKey, reg::kStampSeen, seen) && seen == stamp) return true;
        Sleep(100);
    }
    return false;
}

// Loads the verified DLL into explorer if it isn't there yet. `tap` is the open handle
// from OpenVerifiedTap and must stay open for the duration of this call. With `confirm`,
// also checks that the taskbar was recognized and (if non-zero) that `stamp` arrived.
int LoadIntoExplorer(const UniqueHandle& tap, DWORD explorerWaitMs, bool confirm,
                     DWORD stamp = 0) {
    UniqueHandle mutex(CreateMutexW(nullptr, FALSE, L"Local\\Barely.Injector"));
    if (mutex) {
        DWORD w = WaitForSingleObject(mutex.get(), 60'000);
        if (w != WAIT_OBJECT_0 && w != WAIT_ABANDONED) {
            Say(true, L"Another copy of Barely is busy. Try again in a moment.");
            return kFailed;
        }
    }
    struct Release {
        HANDLE h;
        ~Release() {
            if (h) ReleaseMutex(h);
        }
    } release{mutex.get()};

    if (!tap) return kIntegrity;
    DWORD pid = FindExplorer(explorerWaitMs);
    if (!pid) {
        Say(true, L"The taskbar isn't running (explorer.exe not found). Try again once the "
                  L"desktop has loaded.");
        return kFailed;
    }
    if (!IsTrustedExplorer(pid)) {
        Say(true, L"The taskbar window isn't owned by %%SystemRoot%%\\explorer.exe in your "
                  L"session, so Barely refused to touch it.");
        return kFailed;
    }

    if (!TapLoaded(pid)) {
        HRESULT hr = Inject(pid, SiblingPath(kTapDllName));
        if (FAILED(hr)) {
            Say(true,
                L"Windows refused to load Barely into Explorer (InitializeXamlDiagnosticsEx "
                L"returned 0x%08lX).\nWait a few seconds and try again. If it keeps happening, "
                L"please report it at %ls/issues",
                static_cast<unsigned long>(hr), kRepoUrl);
            return kFailed;
        }
        for (int i = 0; i < 50 && !TapLoaded(pid); ++i) Sleep(100);
        if (!TapLoaded(pid)) {
            Say(true, L"Explorer didn't load %ls. Try again, or report it at %ls/issues",
                kTapDllName, kRepoUrl);
            return kFailed;
        }
    }
    if (!confirm) return kOk;

    switch (QueryTap(pid, 5000)) {
    case TapState::Working:
        if (stamp && !StampReachedExplorer(stamp)) {
            Say(true,
                L"Barely is running in Explorer, but your settings aren't reaching it.\n"
                L"This happens when Barely is started from a sandboxed or virtualized app, which "
                L"gets its own private copy of the registry.\n"
                L"Run Barely from a normal terminal, the Run dialog (Win+R) or File Explorer.");
            return kFailed;
        }
        return kOk;
    case TapState::Outdated:
        Say(true,
            L"A different version of Barely is still loaded in Explorer.\n"
            L"Sign out and back in (or restart Explorer) to finish updating, then run Barely "
            L"again.");
        return kFailed;
    default:
        Say(true,
            L"Barely is loaded, but it couldn't find the taskbar background.\n"
            L"A Windows update has probably changed the taskbar layout (build %lu).\n"
            L"Run `barely --diagnose` and attach the report to an issue at %ls/issues",
            WindowsBuild(), kRepoUrl);
        return kNotRecognized;
    }
}

// ---- Autostart and auto-repair -------------------------------------------------------------

std::wstring XmlEscape(std::wstring_view s) {
    std::wstring out;
    for (wchar_t c : s) {
        switch (c) {
        case L'&': out += L"&amp;"; break;
        case L'<': out += L"&lt;"; break;
        case L'>': out += L"&gt;"; break;
        case L'"': out += L"&quot;"; break;
        default: out += c;
        }
    }
    return out;
}

std::wstring CurrentUserSid() {
    std::wstring result;
    HANDLE token;
    if (!OpenProcessToken(GetCurrentProcess(), TOKEN_QUERY, &token)) return result;
    BYTE buf[256];
    DWORD size = sizeof(buf);
    if (GetTokenInformation(token, TokenUser, buf, size, &size)) {
        LPWSTR sid = nullptr;
        if (ConvertSidToStringSidW(reinterpret_cast<TOKEN_USER*>(buf)->User.Sid, &sid)) {
            result = sid;
            LocalFree(sid);
        }
    }
    CloseHandle(token);
    return result;
}

// A task that runs `barelyw.exe --ensure` every minute while you're signed in. It exits
// within milliseconds when Barely is already loaded, and re-applies it after Explorer
// restarts. Nothing stays running between runs.
bool InstallRepairTask() {
    std::wstring sid = CurrentUserSid();
    if (sid.empty()) return false;
    std::wstring xml =
        L"<?xml version=\"1.0\" encoding=\"UTF-16\"?>\r\n"
        L"<Task version=\"1.2\" xmlns=\"http://schemas.microsoft.com/windows/2004/02/mit/task\">\r\n"
        L"  <RegistrationInfo><Author>AayuShen</Author><Description>Barely: re-applies the "
        L"transparent taskbar after Explorer restarts. Runs for a moment and exits.</Description>"
        L"</RegistrationInfo>\r\n"
        L"  <Triggers><TimeTrigger><Repetition><Interval>PT1M</Interval>"
        L"<StopAtDurationEnd>false</StopAtDurationEnd></Repetition>"
        L"<StartBoundary>2026-01-01T00:00:00</StartBoundary><Enabled>true</Enabled>"
        L"</TimeTrigger></Triggers>\r\n"
        L"  <Principals><Principal id=\"Author\"><UserId>" + XmlEscape(sid) +
        L"</UserId><LogonType>InteractiveToken</LogonType><RunLevel>LeastPrivilege</RunLevel>"
        L"</Principal></Principals>\r\n"
        L"  <Settings><MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>"
        L"<DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>"
        L"<StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>"
        L"<StartWhenAvailable>false</StartWhenAvailable>"
        L"<IdleSettings><StopOnIdleEnd>false</StopOnIdleEnd><RestartOnIdle>false</RestartOnIdle>"
        L"</IdleSettings><Enabled>true</Enabled><ExecutionTimeLimit>PT2M</ExecutionTimeLimit>"
        L"<Priority>7</Priority></Settings>\r\n"
        L"  <Actions Context=\"Author\"><Exec><Command>" + XmlEscape(SiblingPath(L"barelyw.exe")) +
        L"</Command><Arguments>--ensure</Arguments></Exec></Actions>\r\n"
        L"</Task>\r\n";

    wchar_t dir[MAX_PATH], file[MAX_PATH];
    if (!GetTempPathW(MAX_PATH, dir) || !GetTempFileNameW(dir, L"brl", 0, file)) return false;
    bool written = false;
    {
        UniqueHandle h(CreateFileW(file, GENERIC_WRITE, 0, nullptr, CREATE_ALWAYS,
                                   FILE_ATTRIBUTE_TEMPORARY, nullptr));
        if (h) {
            const wchar_t bom = 0xFEFF;
            DWORD n;
            written = WriteFile(h.get(), &bom, sizeof(bom), &n, nullptr) &&
                      WriteFile(h.get(), xml.data(), static_cast<DWORD>(xml.size() * sizeof(wchar_t)),
                                &n, nullptr);
        }
    }
    DWORD code = written ? RunHidden(SystemTool(L"schtasks.exe") + L" /Create /TN \"" + kTaskName +
                                     L"\" /XML \"" + file + L"\" /F")
                         : MAXDWORD;
    DeleteFileW(file);
    return code == 0;
}

bool TaskExists() {
    return RunHidden(SystemTool(L"schtasks.exe") + L" /Query /TN \"" + kTaskName + L"\"") == 0;
}

bool RunKeyExists() {
    return RegGetValueW(HKEY_CURRENT_USER, kRunKey, kRunValue, RRF_RT_REG_SZ, nullptr, nullptr,
                        nullptr) == ERROR_SUCCESS;
}

bool SetAutostart(bool on) {
    if (!on) {
        RegDeleteKeyValueW(HKEY_CURRENT_USER, kRunKey, kRunValue);
        if (TaskExists())
            RunHidden(SystemTool(L"schtasks.exe") + L" /Delete /TN \"" + kTaskName + L"\" /F");
        return !RunKeyExists() && !TaskExists();
    }
    // Quoted, so a path with spaces can't be hijacked by a planted "E:\Program.exe".
    std::wstring cmd = L"\"" + SiblingPath(L"barelyw.exe") + L"\" --ensure";
    bool ok = RegSetKeyValueW(HKEY_CURRENT_USER, kRunKey, kRunValue, REG_SZ, cmd.c_str(),
                              static_cast<DWORD>((cmd.size() + 1) * sizeof(wchar_t))) ==
              ERROR_SUCCESS;
    return InstallRepairTask() && ok;
}

// ---- Command line --------------------------------------------------------------------------

struct Request {
    std::optional<int> opacity, stroke, maximized, light, tint;  // kUnset = remove the setting
    std::optional<bool> autostart;
    bool status = false, diagnose = false, restore = false, ensure = false, settings = false,
         version = false, help = false;
    bool HasSettings() const { return opacity || stroke || maximized || light || tint; }
};

bool ParsePercent(std::wstring_view s, int& out) {
    if (s.empty() || s.size() > 3) return false;
    int v = 0;
    for (wchar_t c : s) {
        if (c < L'0' || c > L'9') return false;
        v = v * 10 + (c - L'0');
    }
    if (v > 100) return false;
    out = v;
    return true;
}

bool ParseColor(std::wstring_view s, int& out) {
    if (!s.empty() && s[0] == L'#') s.remove_prefix(1);
    if (s.size() != 6) return false;
    int v = 0;
    for (wchar_t c : s) {
        if (!std::iswxdigit(c)) return false;
        v = v * 16 + (c <= L'9' ? c - L'0' : (std::towlower(c) - L'a' + 10));
    }
    out = v;
    return true;
}

std::optional<Request> Parse(int argc, wchar_t** argv) {
    Request r;
    for (int i = 1; i < argc; ++i) {
        std::wstring_view a = argv[i];
        std::wstring_view next = i + 1 < argc ? std::wstring_view(argv[i + 1]) : L""sv;
        int v = 0;
        // Option that takes a percentage, or a keyword meaning "unset".
        auto percentOr = [&](std::optional<int>& slot, std::wstring_view keyword) {
            if (!keyword.empty() && next == keyword) slot = kUnset;
            else if (ParsePercent(next, v)) slot = v;
            else return false;
            ++i;
            return true;
        };

        if (a == L"--help" || a == L"-h" || a == L"/?") r.help = true;
        else if (a == L"--version") r.version = true;
        else if (a == L"--status") r.status = true;
        else if (a == L"--diagnose") r.diagnose = true;
        else if (a == L"--restore") r.restore = true;
        else if (a == L"--ensure") r.ensure = true;
        else if (a == L"--settings") r.settings = true;
        else if (a == L"--opacity") { if (!percentOr(r.opacity, L"")) return {}; }
        else if (a == L"--border") { if (!percentOr(r.stroke, L"same")) return {}; }
        else if (a == L"--maximized") { if (!percentOr(r.maximized, L"off")) return {}; }
        else if (a == L"--light") { if (!percentOr(r.light, L"same")) return {}; }
        else if (a == L"--tint") {
            if (next == L"none") r.tint = kUnset;
            else if (ParseColor(next, v)) r.tint = v;
            else return {};
            ++i;
        } else if (a == L"--autostart") {
            if (next == L"on") r.autostart = true;
            else if (next == L"off") r.autostart = false;
            else return {};
            ++i;
        } else if (!r.opacity && ParsePercent(a, v)) {
            r.opacity = v;
        } else {
            return {};
        }
    }
    int const modes = r.status + r.diagnose + r.restore + r.ensure + r.settings + r.version + r.help;
    if (modes > 1 || (modes == 1 && (r.HasSettings() || r.autostart))) return {};
    return r;
}

void Usage(bool error) {
    Say(error,
        L"Barely %ls by AayuShen - a transparent Windows 11 taskbar, nothing left running.\n"
        L"\n"
        L"Usage:\n"
        L"  barely                       apply saved settings (fully clear by default)\n"
        L"  barely <0-100>               taskbar opacity in percent\n"
        L"  barely [options]             change one or more settings and apply them:\n"
        L"      --opacity <0-100>          background opacity\n"
        L"      --border <0-100|same>      top border line opacity\n"
        L"      --tint <#RRGGBB|none>      background colour\n"
        L"      --maximized <0-100|off>    opacity while the active window is maximized\n"
        L"      --light <0-100|same>       opacity when Windows is in light mode\n"
        L"      --autostart <on|off>       apply at sign-in and re-apply after Explorer restarts\n"
        L"  barely --settings            open the settings window\n"
        L"  barely --status              show what Barely is doing\n"
        L"  barely --diagnose            write a report to attach to bug reports\n"
        L"  barely --restore             stock taskbar, autostart off\n"
        L"  barely --version\n"
        L"\n"
        L"Docs and issues: %ls",
        kVersion, kRepoUrl);
}

// ---- Commands ------------------------------------------------------------------------------

int CmdApply(Request r) {
    if (int rc = CheckWindows(true)) return rc;
    UniqueHandle tap = OpenVerifiedTap();  // before touching anything else
    if (!tap) return kIntegrity;

    if (!r.opacity && ReadSettings().opacity < 0) r.opacity = 0;  // first run: fully clear
    bool ok = true;
    if (r.stroke) ok = WriteSetting(reg::kStroke, *r.stroke) && ok;
    if (r.maximized) ok = WriteSetting(reg::kMaximized, *r.maximized) && ok;
    if (r.light) ok = WriteSetting(reg::kLight, *r.light) && ok;
    if (r.tint) ok = WriteSetting(reg::kTint, *r.tint) && ok;
    if (r.opacity) ok = WriteSetting(reg::kOpacity, *r.opacity) && ok;  // the master switch
    DWORD const stamp = static_cast<DWORD>(GetTickCount64()) | 1;
    ok = WriteSetting(reg::kStamp, static_cast<int>(stamp & 0x7FFFFFFF)) && ok;  // last
    if (!ok) {
        Say(true, L"Couldn't save settings to HKCU\\%ls.", kRegKey);
        return kFailed;
    }
    if (r.autostart && !SetAutostart(*r.autostart)) {
        Say(true, L"Couldn't update autostart (Run key / scheduled task).");
        return kFailed;
    }

    if (int rc = LoadIntoExplorer(tap, 5000, true, stamp & 0x7FFFFFFF)) return rc;
    Say(false, L"Taskbar: %ls.", Describe(ReadSettings()).c_str());
    if (r.autostart) Say(false, L"Autostart %ls.", *r.autostart ? L"on" : L"off");
    return kOk;
}

int CmdAutostart(bool on) {
    if (on && GetFileAttributesW(SiblingPath(L"barelyw.exe").c_str()) == INVALID_FILE_ATTRIBUTES) {
        Say(true, L"barelyw.exe not found next to barely.exe.");
        return kFailed;
    }
    if (!SetAutostart(on)) {
        Say(true, L"Couldn't update autostart (Run key / scheduled task).");
        return kFailed;
    }
    Say(false, on ? L"Autostart on: Barely applies at sign-in and re-applies within a minute "
                    L"after Explorer restarts."
                  : L"Autostart off.");
    return kOk;
}

// Run at sign-in and by the auto-repair task. Silent, and quick when there's nothing to do.
int CmdEnsure() {
    g_quiet = true;
    if (ReadSettings().opacity < 0) return kOk;
    if (DWORD pid = FindExplorer(0); pid && IsTrustedExplorer(pid) && TapLoaded(pid)) return kOk;
    if (int rc = CheckWindows(false)) return rc;
    UniqueHandle tap = OpenVerifiedTap();
    if (!tap) return kIntegrity;
    return LoadIntoExplorer(tap, 30'000, false);
}

int CmdRestore() {
    bool ok = true;
    for (const wchar_t* name :
         {reg::kOpacity, reg::kStroke, reg::kMaximized, reg::kLight, reg::kTint})
        ok = WriteSetting(name, kUnset) && ok;
    ok = SetAutostart(false) && ok;
    if (!ok) {
        Say(true, L"Couldn't remove all of Barely's settings.");
        return kFailed;
    }
    Say(false, L"Restored the stock taskbar. Autostart is off.");
    return kOk;
}

int CmdStatus() {
    Settings const s = ReadSettings();
    DWORD const build = WindowsBuild();
    std::wstring out = L"Barely " + std::wstring(kVersion) + L" by AayuShen\n\n";
    out += L"Windows build:  " + std::to_wstring(build) +
           (build < kMinBuild ? L" (not Windows 11, unsupported)"
                              : IsTestedBuild(build) ? L" (tested)" : L" (not tested yet)") +
           L"\n";

    DWORD pid = FindExplorer(0);
    if (!pid) {
        out += L"Explorer:       not running\n";
    } else {
        out += L"Explorer:       running (pid " + std::to_wstring(pid) + L")\n";
        out += L"Barely:         ";
        switch (QueryTap(pid, 0)) {
        case TapState::NotLoaded:
            out += s.opacity < 0 ? L"not loaded\n" : L"not loaded - run `barely` to apply\n";
            break;
        case TapState::Outdated:
            out += L"an older version is loaded - restart Explorer to update\n";
            break;
        case TapState::Unrecognized:
            out += L"loaded, but the taskbar background wasn't found - run `barely --diagnose`\n";
            break;
        case TapState::Working: {
            DWORD targets = 0;
            ReadDword(kRegRuntimeKey, reg::kTargets, targets);
            out += L"loaded, styling " + std::to_wstring(targets) + L" taskbar element(s)\n";
            break;
        }
        }
    }
    out += L"Settings:       " + Describe(s) + L"\n";
    bool const run = RunKeyExists(), task = TaskExists();
    out += L"Autostart:      ";
    out += run && task ? L"on (sign-in + auto-repair task)"
           : run       ? L"partly on (sign-in only) - run `barely --autostart on` to repair"
           : task      ? L"partly on (auto-repair only) - run `barely --autostart on` to repair"
                       : L"off";
    Say(false, L"%ls", out.c_str());
    return kOk;
}

int CmdDiagnose() {
    if (int rc = CheckWindows(false)) return rc;
    UniqueHandle tap = OpenVerifiedTap();
    if (!tap) return kIntegrity;
    if (int rc = LoadIntoExplorer(tap, 5000, false)) return rc;

    DWORD request = static_cast<DWORD>(GetTickCount64()) | 1, done = 0;
    RegSetKeyValueW(HKEY_CURRENT_USER, kRegKey, reg::kDiagRequest, REG_DWORD, &request,
                    sizeof(request));
    for (int i = 0; i < 50; ++i) {
        if (ReadDword(kRegRuntimeKey, reg::kDiagDone, done) && done == request) break;
        Sleep(100);
    }
    wchar_t path[MAX_PATH] = {};
    if (done != request || !DiagnosePath(path)) {
        Say(true, L"Barely inside Explorer didn't answer. If you just updated Barely, restart "
                  L"Explorer and try again.");
        return kFailed;
    }
#ifndef BARELY_GUI
    if (FILE* f = nullptr; _wfopen_s(&f, path, L"rb") == 0 && f) {
        char buf[4096];
        size_t n;
        while ((n = fread(buf, 1, sizeof(buf), f)) > 0) fwrite(buf, 1, n, stdout);
        fclose(f);
    }
#endif
    Say(false, L"\nReport saved to %ls\nAttach it to an issue at %ls/issues", path, kRepoUrl);
    return kOk;
}

// ---- Settings window -----------------------------------------------------------------------

enum : int {
    IDC_OPACITY = 101,
    IDC_MAXCHECK,
    IDC_MAXSLIDER,
    IDC_TINTCHECK,
    IDC_TINTBUTTON,
    IDC_AUTOSTART,
    IDC_RESTORE,
};

struct SettingsUi {
    HWND wnd{}, opacityLabel{}, opacity{}, opacityValue{}, maxCheck{}, maxSlider{}, maxValue{},
        tintCheck{}, tintButton{}, autostart{}, restore{}, close{};
    HFONT font{};
    UINT dpi = 96;
    int tint = 0x000000;
    COLORREF custom[16]{};
} g_ui;

int Px(int v) { return MulDiv(v, static_cast<int>(g_ui.dpi), 96); }

constexpr int kClientW = 344, kClientH = 268;

void LayoutSettings() {
    NONCLIENTMETRICSW ncm{sizeof(ncm)};
    SystemParametersInfoForDpi(SPI_GETNONCLIENTMETRICS, sizeof(ncm), &ncm, 0, g_ui.dpi);
    if (g_ui.font) DeleteObject(g_ui.font);
    g_ui.font = CreateFontIndirectW(&ncm.lfMessageFont);
    struct { HWND h; int x, y, w, ht; } const items[] = {
        {g_ui.opacityLabel, 14, 12, 300, 20}, {g_ui.opacity, 8, 34, 272, 30},
        {g_ui.opacityValue, 286, 40, 46, 20}, {g_ui.maxCheck, 14, 80, 318, 22},
        {g_ui.maxSlider, 8, 104, 272, 30},    {g_ui.maxValue, 286, 110, 46, 20},
        {g_ui.tintCheck, 14, 150, 150, 24},   {g_ui.tintButton, 172, 148, 108, 28},
        {g_ui.autostart, 14, 190, 318, 24},   {g_ui.restore, 14, 228, 170, 30},
        {g_ui.close, 252, 228, 80, 30},
    };
    for (auto const& i : items) {
        MoveWindow(i.h, Px(i.x), Px(i.y), Px(i.w), Px(i.ht), TRUE);
        SendMessageW(i.h, WM_SETFONT, reinterpret_cast<WPARAM>(g_ui.font), TRUE);
    }
}

void ShowPercent(HWND label, int v) {
    wchar_t text[8];
    swprintf_s(text, L"%d%%", v);
    SetWindowTextW(label, text);
}

void ShowTint() {
    wchar_t text[16];
    swprintf_s(text, L"#%06X...", g_ui.tint);
    SetWindowTextW(g_ui.tintButton, text);
}

bool Checked(HWND h) { return SendMessageW(h, BM_GETCHECK, 0, 0) == BST_CHECKED; }
int SliderPos(HWND h) { return static_cast<int>(SendMessageW(h, TBM_GETPOS, 0, 0)); }

// Window procedure for 'barely --settings'. Every control writes its setting to the registry
// as soon as it changes; the DLL inside Explorer picks that up and restyles the taskbar live,
// so this window never talks to Explorer directly.
//   WM_CREATE      build the controls and load the current settings into them
//   WM_HSCROLL     slider moved: opacity, or maximized opacity when that option is on
//   WM_COMMAND     checkboxes, colour picker, autostart, restore, close
//   WM_DPICHANGED  re-layout for the new monitor's scaling
LRESULT CALLBACK SettingsProc(HWND wnd, UINT msg, WPARAM wParam, LPARAM lParam) {
    switch (msg) {
    case WM_CREATE: {
        g_ui.wnd = wnd;
        g_ui.dpi = GetDpiForWindow(wnd);
        auto make = [&](const wchar_t* cls, const wchar_t* text, DWORD style, int id) {
            return CreateWindowExW(0, cls, text, WS_CHILD | WS_VISIBLE | style, 0, 0, 0, 0, wnd,
                                   reinterpret_cast<HMENU>(static_cast<INT_PTR>(id)),
                                   GetModuleHandleW(nullptr), nullptr);
        };
        g_ui.opacityLabel = make(WC_STATICW, L"Taskbar opacity", 0, 0);
        g_ui.opacity = make(TRACKBAR_CLASSW, L"", WS_TABSTOP | TBS_HORZ | TBS_NOTICKS, IDC_OPACITY);
        g_ui.opacityValue = make(WC_STATICW, L"", 0, 0);
        g_ui.maxCheck = make(WC_BUTTONW, L"When the active window is maximized, use:",
                             WS_TABSTOP | BS_AUTOCHECKBOX, IDC_MAXCHECK);
        g_ui.maxSlider =
            make(TRACKBAR_CLASSW, L"", WS_TABSTOP | TBS_HORZ | TBS_NOTICKS, IDC_MAXSLIDER);
        g_ui.maxValue = make(WC_STATICW, L"", 0, 0);
        g_ui.tintCheck = make(WC_BUTTONW, L"Tint colour", WS_TABSTOP | BS_AUTOCHECKBOX, IDC_TINTCHECK);
        g_ui.tintButton = make(WC_BUTTONW, L"", WS_TABSTOP | BS_PUSHBUTTON, IDC_TINTBUTTON);
        g_ui.autostart = make(WC_BUTTONW, L"Start with Windows (re-applies after Explorer restarts)",
                              WS_TABSTOP | BS_AUTOCHECKBOX, IDC_AUTOSTART);
        g_ui.restore = make(WC_BUTTONW, L"Restore stock taskbar", WS_TABSTOP | BS_PUSHBUTTON, IDC_RESTORE);
        g_ui.close = make(WC_BUTTONW, L"Close", WS_TABSTOP | BS_DEFPUSHBUTTON, IDCANCEL);

        Settings const s = ReadSettings();
        for (HWND slider : {g_ui.opacity, g_ui.maxSlider}) {
            SendMessageW(slider, TBM_SETRANGE, TRUE, MAKELPARAM(0, 100));
            SendMessageW(slider, TBM_SETPAGESIZE, 0, 10);
        }
        int const op = s.opacity < 0 ? 0 : s.opacity;
        int const mx = s.maximized < 0 ? 100 : s.maximized;
        SendMessageW(g_ui.opacity, TBM_SETPOS, TRUE, op);
        SendMessageW(g_ui.maxSlider, TBM_SETPOS, TRUE, mx);
        ShowPercent(g_ui.opacityValue, op);
        ShowPercent(g_ui.maxValue, mx);
        SendMessageW(g_ui.maxCheck, BM_SETCHECK, s.maximized >= 0 ? BST_CHECKED : BST_UNCHECKED, 0);
        EnableWindow(g_ui.maxSlider, s.maximized >= 0);
        g_ui.tint = s.tint < 0 ? 0x000000 : s.tint;
        SendMessageW(g_ui.tintCheck, BM_SETCHECK, s.tint >= 0 ? BST_CHECKED : BST_UNCHECKED, 0);
        ShowTint();
        SendMessageW(g_ui.autostart, BM_SETCHECK,
                     RunKeyExists() || TaskExists() ? BST_CHECKED : BST_UNCHECKED, 0);

        LayoutSettings();
        RECT rc{0, 0, Px(kClientW), Px(kClientH)};
        AdjustWindowRectExForDpi(&rc, GetWindowLongW(wnd, GWL_STYLE), FALSE,
                                 GetWindowLongW(wnd, GWL_EXSTYLE), g_ui.dpi);
        SetWindowPos(wnd, nullptr, 0, 0, rc.right - rc.left, rc.bottom - rc.top,
                     SWP_NOMOVE | SWP_NOZORDER);
        return 0;
    }
    case WM_HSCROLL: {
        HWND src = reinterpret_cast<HWND>(lParam);
        int const pos = SliderPos(src);
        if (src == g_ui.opacity) {
            ShowPercent(g_ui.opacityValue, pos);
            WriteSetting(reg::kOpacity, pos);  // the DLL applies it live
        } else if (src == g_ui.maxSlider) {
            ShowPercent(g_ui.maxValue, pos);
            if (Checked(g_ui.maxCheck)) WriteSetting(reg::kMaximized, pos);
        }
        return 0;
    }
    case WM_COMMAND:
        switch (LOWORD(wParam)) {
        case IDC_MAXCHECK: {
            bool const on = Checked(g_ui.maxCheck);
            EnableWindow(g_ui.maxSlider, on);
            WriteSetting(reg::kMaximized, on ? SliderPos(g_ui.maxSlider) : kUnset);
            return 0;
        }
        case IDC_TINTCHECK:
            WriteSetting(reg::kTint, Checked(g_ui.tintCheck) ? g_ui.tint : kUnset);
            return 0;
        case IDC_TINTBUTTON: {
            CHOOSECOLORW cc{sizeof(cc)};
            cc.hwndOwner = wnd;
            cc.rgbResult = RGB(g_ui.tint >> 16, (g_ui.tint >> 8) & 0xFF, g_ui.tint & 0xFF);
            cc.lpCustColors = g_ui.custom;
            cc.Flags = CC_FULLOPEN | CC_RGBINIT;
            if (ChooseColorW(&cc)) {
                g_ui.tint = (GetRValue(cc.rgbResult) << 16) | (GetGValue(cc.rgbResult) << 8) |
                            GetBValue(cc.rgbResult);
                ShowTint();
                SendMessageW(g_ui.tintCheck, BM_SETCHECK, BST_CHECKED, 0);
                WriteSetting(reg::kTint, g_ui.tint);
            }
            return 0;
        }
        case IDC_AUTOSTART: {
            bool const on = Checked(g_ui.autostart);
            if (!SetAutostart(on)) {
                MessageBoxW(wnd, L"Couldn't update autostart.", L"Barely", MB_ICONERROR);
                SendMessageW(g_ui.autostart, BM_SETCHECK, on ? BST_UNCHECKED : BST_CHECKED, 0);
            }
            return 0;
        }
        case IDC_RESTORE:
            g_quiet = true;
            CmdRestore();
            DestroyWindow(wnd);
            return 0;
        case IDCANCEL:
            DestroyWindow(wnd);
            return 0;
        }
        break;
    case WM_DPICHANGED: {
        g_ui.dpi = HIWORD(wParam);
        auto const* r = reinterpret_cast<const RECT*>(lParam);
        SetWindowPos(wnd, nullptr, r->left, r->top, r->right - r->left, r->bottom - r->top,
                     SWP_NOZORDER | SWP_NOACTIVATE);
        LayoutSettings();
        return 0;
    }
    case WM_CLOSE:
        DestroyWindow(wnd);
        return 0;
    case WM_DESTROY:
        PostQuitMessage(0);
        return 0;
    }
    return DefWindowProcW(wnd, msg, wParam, lParam);
}

int CmdSettings() {
    if (int rc = CheckWindows(false)) return rc;
    {
        UniqueHandle tap = OpenVerifiedTap();
        if (!tap) return kIntegrity;
        if (ReadSettings().opacity < 0) WriteSetting(reg::kOpacity, 0);
        if (int rc = LoadIntoExplorer(tap, 5000, true)) return rc;
    }

    INITCOMMONCONTROLSEX icc{sizeof(icc), ICC_BAR_CLASSES | ICC_STANDARD_CLASSES};
    InitCommonControlsEx(&icc);
    WNDCLASSEXW wc{sizeof(wc)};
    wc.lpfnWndProc = SettingsProc;
    wc.hInstance = GetModuleHandleW(nullptr);
    wc.hCursor = LoadCursorW(nullptr, IDC_ARROW);
    wc.hbrBackground = reinterpret_cast<HBRUSH>(COLOR_BTNFACE + 1);
    wc.lpszClassName = L"BarelySettings";
    wc.hIcon = LoadIconW(nullptr, IDI_APPLICATION);
    RegisterClassExW(&wc);
    HWND wnd = CreateWindowExW(0, wc.lpszClassName, L"Barely settings",
                               WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX,
                               CW_USEDEFAULT, CW_USEDEFAULT, 400, 320, nullptr, nullptr,
                               wc.hInstance, nullptr);
    if (!wnd) return kFailed;
    ShowWindow(wnd, SW_SHOW);

    MSG msg;
    while (GetMessageW(&msg, nullptr, 0, 0) > 0) {
        if (!IsDialogMessageW(wnd, &msg)) {
            TranslateMessage(&msg);
            DispatchMessageW(&msg);
        }
    }
    if (g_ui.font) DeleteObject(g_ui.font);
    return kOk;
}

}  // namespace

int wmain(int argc, wchar_t** argv) {
    // Never pick up DLLs from the current or application directory.
    SetDefaultDllDirectories(LOAD_LIBRARY_SEARCH_SYSTEM32);

    std::optional<Request> req = Parse(argc, argv);
    if (!req) {
        Usage(true);
        return kUsage;
    }
    if (req->help) {
        Usage(false);
        return kOk;
    }
    if (req->version) {
        Say(false, L"Barely %ls by AayuShen", kVersion);
        return kOk;
    }
    if (req->ensure) g_quiet = true;
    if (IsElevated()) {
        Say(true, L"Run Barely as a normal user, not as administrator. It doesn't need admin "
                  L"rights.");
        return kElevated;
    }

    if (req->status) return CmdStatus();
    if (req->diagnose) return CmdDiagnose();
    if (req->restore) return CmdRestore();
    if (req->ensure) return CmdEnsure();
    if (req->settings) return CmdSettings();
    if (req->autostart && !req->HasSettings()) return CmdAutostart(*req->autostart);
    return CmdApply(*req);
}
